// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Settings → QuickLinks*
 */
export interface SettingsDocumentDataQuicklinksItem {
  /**
   * section_1 field in *Settings → QuickLinks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.quicklinks[].section_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_1: prismic.KeyTextField;

  /**
   * section_2 field in *Settings → QuickLinks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.quicklinks[].section_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_2: prismic.KeyTextField;

  /**
   * section_3 field in *Settings → QuickLinks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.quicklinks[].section_3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_3: prismic.KeyTextField;

  /**
   * section_4 field in *Settings → QuickLinks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.quicklinks[].section_4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_4: prismic.KeyTextField;

  /**
   * section_5 field in *Settings → QuickLinks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.quicklinks[].section_5
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_5: prismic.KeyTextField;

  /**
   * section_6 field in *Settings → QuickLinks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.quicklinks[].section_6
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_6: prismic.KeyTextField;
}

/**
 * Item in *Settings → Newsroom*
 */
export interface SettingsDocumentDataNewsroomItem {
  /**
   * news_1 field in *Settings → Newsroom*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.newsroom[].news_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  news_1: prismic.KeyTextField;

  /**
   * news_2 field in *Settings → Newsroom*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.newsroom[].news_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  news_2: prismic.KeyTextField;

  /**
   * news_3 field in *Settings → Newsroom*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.newsroom[].news_3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  news_3: prismic.KeyTextField;

  /**
   * news_4 field in *Settings → Newsroom*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.newsroom[].news_4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  news_4: prismic.KeyTextField;

  /**
   * news_5 field in *Settings → Newsroom*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.newsroom[].news_5
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  news_5: prismic.KeyTextField;

  /**
   * news_1_date field in *Settings → Newsroom*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.newsroom[].news_1_date
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  news_1_date: prismic.KeyTextField;

  /**
   * news_2_date field in *Settings → Newsroom*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.newsroom[].news_2_date
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  news_2_date: prismic.KeyTextField;

  /**
   * news_3_date field in *Settings → Newsroom*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.newsroom[].news_3_date
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  news_3_date: prismic.KeyTextField;

  /**
   * news_4_date field in *Settings → Newsroom*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.newsroom[].news_4_date
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  news_4_date: prismic.KeyTextField;

  /**
   * news_5_date field in *Settings → Newsroom*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.newsroom[].news_5_date
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  news_5_date: prismic.KeyTextField;
}

/**
 * Item in *Settings → Updates_from_lapd*
 */
export interface SettingsDocumentDataUpdatesFromLapdItem {
  /**
   * update_title_1 field in *Settings → Updates_from_lapd*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.updates_from_lapd[].update_title_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  update_title_1: prismic.KeyTextField;

  /**
   * update_image_1 field in *Settings → Updates_from_lapd*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.updates_from_lapd[].update_image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  update_image_1: prismic.ImageField<never>;

  /**
   * update_description_1 field in *Settings → Updates_from_lapd*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.updates_from_lapd[].update_description_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  update_description_1: prismic.KeyTextField;

  /**
   * update_title_2 field in *Settings → Updates_from_lapd*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.updates_from_lapd[].update_title_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  update_title_2: prismic.KeyTextField;

  /**
   * update_image_2 field in *Settings → Updates_from_lapd*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.updates_from_lapd[].update_image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  update_image_2: prismic.ImageField<never>;

  /**
   * update_description_2 field in *Settings → Updates_from_lapd*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.updates_from_lapd[].update_description_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  update_description_2: prismic.KeyTextField;
}

/**
 * Item in *Settings → Contact_details*
 */
export interface SettingsDocumentDataContactDetailsItem {
  /**
   * section_2 field in *Settings → Contact_details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_details[].section_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_2: prismic.KeyTextField;

  /**
   * section_2_details field in *Settings → Contact_details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_details[].section_2_details
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_2_details: prismic.KeyTextField;

  /**
   * section_3 field in *Settings → Contact_details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_details[].section_3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_3: prismic.KeyTextField;

  /**
   * section_3_details field in *Settings → Contact_details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_details[].section_3_details
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_3_details: prismic.KeyTextField;

  /**
   * section_1 field in *Settings → Contact_details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_details[].section_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_1: prismic.KeyTextField;

  /**
   * section_1_details field in *Settings → Contact_details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_details[].section_1_details
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_1_details: prismic.KeyTextField;
}

type SettingsDocumentDataSlicesSlice = never;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * description field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * site title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * data_description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.data_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  data_description: prismic.KeyTextField;

  /**
   * Heading field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Subheading field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.subheading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * daily_update field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.daily_update
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  daily_update: prismic.KeyTextField;

  /**
   * your_lapd field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.your_lapd
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  your_lapd: prismic.KeyTextField;

  /**
   * get_service field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.get_service
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  get_service: prismic.KeyTextField;

  /**
   * crime_info field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.crime_info
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  crime_info: prismic.KeyTextField;

  /**
   * get_involved field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.get_involved
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  get_involved: prismic.KeyTextField;

  /**
   * news field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.news
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  news: prismic.KeyTextField;

  /**
   * contact field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact: prismic.KeyTextField;

  /**
   * homepage_image1 field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.homepage_image1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  homepage_image1: prismic.ImageField<never>;

  /**
   * homepage_image2 field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.homepage_image2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  homepage_image2: prismic.ImageField<never>;

  /**
   * homepage_image3 field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.homepage_image3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  homepage_image3: prismic.ImageField<never>;

  /**
   * homepage_image4 field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.homepage_image4
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  homepage_image4: prismic.ImageField<never>;

  /**
   * homepage_image5 field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.homepage_image5
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  homepage_image5: prismic.ImageField<never>;

  /**
   * homepage_image6 field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.homepage_image6
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  homepage_image6: prismic.ImageField<never>;

  /**
   * message_from_chief_image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.message_from_chief_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  message_from_chief_image: prismic.ImageField<never>;

  /**
   * QuickLinks field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.quicklinks[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  quicklinks: prismic.GroupField<Simplify<SettingsDocumentDataQuicklinksItem>>;

  /**
   * Newsroom field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.newsroom[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  newsroom: prismic.GroupField<Simplify<SettingsDocumentDataNewsroomItem>>;

  /**
   * Updates_from_lapd field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.updates_from_lapd[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  updates_from_lapd: prismic.GroupField<
    Simplify<SettingsDocumentDataUpdatesFromLapdItem>
  >;

  /**
   * Contact_details field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_details[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  contact_details: prismic.GroupField<
    Simplify<SettingsDocumentDataContactDetailsItem>
  >;

  /**
   * footer_image_1 field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_image_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  footer_image_1: prismic.ImageField<never>;

  /**
   * footer_image_2 field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_image_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  footer_image_2: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SettingsDocumentDataSlicesSlice> /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: settings.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: settings.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes = SettingsDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataQuicklinksItem,
      SettingsDocumentDataNewsroomItem,
      SettingsDocumentDataUpdatesFromLapdItem,
      SettingsDocumentDataContactDetailsItem,
      SettingsDocumentDataSlicesSlice,
      AllDocumentTypes,
    };
  }
}
