import type { Metadata } from 'next'

import Header from '@/component/Header'
import Footer from '@/component/Footer'
import { Margin } from '@mui/icons-material'


export const metadata: Metadata = {
  title: 'Lapd',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <head></head>
      <body style={{margin:"0px"}}>
       <Header />
        {children}
        <Footer />
        </body>
    </html>
  )
}
